### ISSUE TITLE
GNSS reception dependencies

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/delta#60]
The current GNSS reception depends on 

http://magma.geonet.org.nz/services/gps/network?networkName=all&status=operational

and

site services like:

http://magma.geonet.org.nz/services/gps/reception?markCode=TAUP

**Comment by elidana** [comment]
The other "production" scripts I'm aware of are also using these urls :
http://magma.geonet.org.nz/ws-delta/site?type=cgps&status=Closed
http://magma.geonet.org.nz/ws-delta/site?type=cgps&status=Operational

These scripts are used to:
- run the daily GPS processing with Gamit/GlobK
- upload the GPS time series to FITS
- distribute metadata information through this ftp location ftp://ftp.geonet.org.nz/gps/sitelogs/ . This was requested by LINZ in 2014-15 (the provision of metadata in this format is under our contract with LINZ)


The _patchy_ scripts that are used for the above can be found in two places:
https://github.com/GeoNet/docker-gamit/scripts
https://github.com/GeoNet/gps-scripts/sitelogs

Those can be "easily" replace/cleverized and streamlined, so here I'm just trying to help identifying the existing dependencies. I'm happy to toss/review/replace anything that looks like a scary zombie.

**Comment by elidana** [comment]
@dc735 , @ozym this is the list of oracle delta XML files that are used across various gps data reception / metadata distribution scripts.

I'll work a list of the scripts that will need to be updated with the S3 bucket address

**Comment by elidana** [comment]
I hope I got them all...

List of scripts/config files that are pointing to _magma.geonet.org.nz_ XML files to read metadata from the Oracle db. 
All of those are saved (and will need to be updated) in the GitHub/GeoNet repo

#### Table 1. production scripts
repo - script/config file | to be deployed on | where
--|--|--
`/dmc-config/reception/sbin/get-reception-config.pl` | _avdps01_, _rhombus_ , _sublime_ | `/home/gpsin/sbin`
`/gps-scripts/fits/qc2fits.config` | _avdps01_ | `/home/gpsin/etc/`
`/gps-scripts/sitelogs/delta2siteinfo.config` | _avdps01_ | `/home/gpsin/sitelogs`
`/docker-gamit/scripts/gamit_scripts.config` | _avdps02_ , _avdps03_ | `/home/elidana/git/`

#### Table 2. non-production scripts 
script/config file on `gps-scripts` repo  | usually runs on
---|---
`netr9/scripts/py-scripts/config_upgrade_receiver.py` | _rhombus_
`netr9/scripts/py-scripts/station_info_update.py` | don't think it's still used
`netr9/scripts/py-scripts/test_config_upgrade_receiver.py` | don't think it's still used
`get_netr_lists.py` | _rally_




#### THINGS TO CHECK
1) is there any script that extracts **DELTA_RINEX_HEAD_COMM** table from Oracle-db?
Don't think so, because on _rhombus_  the file timestamp is quite old  `-rw-r--r--. 1 gpsin gpsin  1770 Nov 19  2012 rinex_com_headers.xml`. That one is used by rinex creations scripts, and should be a local copy of `/dmc-config/reception/etc/rinex_com_headers.xml` maintained on `dmc-config` git-repo. 
On the git-delta, part of it is dumped into `tools/rinexml/site_test.go` and `tools/rinexml/main.go`
Need a bit more plumbing here? See difference between `header_comment_text` field for
http://magma.geonet.org.nz/services/gps/reception?markCode=quar
http://magma.geonet.org.nz/services/gps/reception?markCode=taup
http://magma.geonet.org.nz/services/gps/reception?markCode=fale
http://magma.geonet.org.nz/services/gps/reception?markCode=hana

**Comment by elidana** [comment]
S3 bucket is finally ready, as per https://github.com/GeoNet/tickets/issues/1585
The python codes that are using _magma_ api to read metadata are using `lxml` to parse the xml file.
'lxml` parsing of the geonet-meta S3 xml fails because `lxml` does not support _https_ 
a further library is needed for python codes

```
Python 2.6.6 (r266:84292, Aug 18 2016, 12:06:14) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from lxml import etree
>>> from urllib2 import urlopen
>>> etree.parse(urlopen("https://s3-ap-southeast-2.amazonaws.com/geonet-meta/config/rinex/taup.xml"))
<lxml.etree._ElementTree object at 0x181fb48>
```

/cc @staylorofford @dc735

**Comment by elidana** [comment]
All GPS-reception scripts that are in production are now reading metadata from the XML files on S3

/cc @nbalfour @quiffman @dc735 @ozym @staylorofford

**Comment by elidana** [comment]
The new version get-reception config script is now up and running on `sublime` 
We can leave it for a day and check that things are working as expected and if so, copy it to `rhombus` tomorrow or next week.
Thoughts, @staylorofford and @dc735 ?

stations that are now using S3-xml files are:

```
AHTI
ANAU
ARTA
AUKT
AVLN
CLIM
CMBL
CNST
CORM
DURV
FRTN
GLDB
GNBK
GUNR
HANA
KAPT
KAWK
KOKO
MAHO
MAKO
MANG
MING
MKNO
MTPR
NLSN
OHIN
OROA
OTAK
PAWA
PILK
PKNO
PRTU
PUKE
PYGR
RAHI
RAKW
RAUM
RAWI
RDLV
RGAR
RGHL
RGKA
RGLI
RGMK
RGMT
RGON
RGRR
RGTA
RGUT
RGWC
RGWI
RGWV
RIPA
SNST
TAKP
TAUP
TGHO
TGHR
TGOH
TGRA
TGRI
TGTK
TGWH
TKAR
TORY
TRAV
TRNG
VEXA
VGFW
VGKR
VGMO
VGMT
VGNG
VGNT
VGOB
VGOT
VGPK
VGTR
VGTS
VGWH
VGWN
VGWT
WAHU
WAIM
WEST
WGTT
WHKT
WITH
```

**Comment by staylorofford** [comment]
I have checked WAIM and RGUT's most recent hourly RINEX files and nothing is out of the ordinary. Also there are no missing RINEX files since the Sublime code update.

I'd give Rhombus script updates a green light.

**Comment by elidana** [comment]
all scripts are now ready to switch to use S3-xml files instead of magma
